[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
]

[window]
decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.0
