[general]
import = [
    "~/.config/alacritty/themes/current_theme.toml"
]

[window]
decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0
