#! /bin/sh

#~/.screenlayout/withmsi.sh &
~/.config/polybar/launch.sh &
setxkbmap 'us,ru' -option 'grp:win_space_toggle' &
xset r rate 250 35
xset -b
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xsetroot -cursor_name left_ptr &
picom -b &
# xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &
feh --bg-fill ~/.local/share/backgrounds/thinkpad.png &
pgrep -x polkit-gnome-authentication-agent-1 > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

# # Настроить мониторы
# bspc monitor eDP-1 -d I II III bspc monitor HDMI-1-0 -d IV V VI
# # Получаем список мониторов
# monitors=($(bspc query -M --names))
# 
# # Если мониторов два
# if [[ ${#monitors[@]} -eq 2 ]]; then
#      bspc monitor ${monitors[1]} -d 1 2 3 4 5   # Первый монитор
#      bspc monitor ${monitors[0]} -d 6 7  # Второй монитор
# else
#    # Если один монитор, назначаем все workspace'ы на него
#      bspc monitor ${monitors[1]} -d 1 2 3 4 5 6 7
# fi
#

bspc monitor eDP1 -d 1 2 3 4 5 6 7
# bspc monitor HDMI-1-0 -d 8

# Переместить окно на следующий монитор
# bspc node -m next --follow

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

#bspc rule -a Telegram 	desktop='^3'
#bspc rule -a discord  	desktop='^3'
#bspc rule -a btop++     	desktop='^4' focus=on 
bspc rule -a AmneziaVPN focus=on  state=floating
#bspc rule -a Alacritty:cmus	    desktop='^5' focus=on
#bspc rule -a Alacritty:cava	    desktop='^5' 
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Основные цвета Dracula
bspc config normal_border_color   "#44475a"    # Неактивное окно
bspc config active_border_color   "#ff79c6"    # Активное окно (розовый)
bspc config focused_border_color  "#bd93f9"    # Фокусное окно (фиолетовый)
bspc config presel_feedback_color "#bd93f9"    # Предпросмотр сплита (красный)
